#define PLUS 1
#define MINUS 2
#define MULT 3
#define DIVIDE 4
#define MODULO 5
#define EXP 6
#define LPAREN 7
#define RPAREN 8 
#define EQUALS 9
#define LTHAN 10
#define GTHAN 11
#define COLON 12
#define COMMA 13
#define SCOLON 14
#define PERIOD 15
#define QUOTE 16
#define DQUOTE 17
#define NUMBER 18 
#define IDENT 19
#define TAGIDENT 20
#define ENDTAGHEAD 21